// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ScopeProperties Properties of a scope.
//
// swagger:model ScopeProperties
type ScopeProperties interface{}
