// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/radius-project/radius/pkg/cli/cmd/shutdown (interfaces: PGBackupClient)
//
// Generated by this command:
//
//	mockgen -typed -destination=./pkg/cli/cmd/shutdown/mock_pgbackupclient.go -package=shutdown github.com/radius-project/radius/pkg/cli/cmd/shutdown PGBackupClient
//

// Package shutdown is a generated GoMock package.
package shutdown

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPGBackupClient is a mock of PGBackupClient interface.
type MockPGBackupClient struct {
	ctrl     *gomock.Controller
	recorder *MockPGBackupClientMockRecorder
	isgomock struct{}
}

// MockPGBackupClientMockRecorder is the mock recorder for MockPGBackupClient.
type MockPGBackupClientMockRecorder struct {
	mock *MockPGBackupClient
}

// NewMockPGBackupClient creates a new mock instance.
func NewMockPGBackupClient(ctrl *gomock.Controller) *MockPGBackupClient {
	mock := &MockPGBackupClient{ctrl: ctrl}
	mock.recorder = &MockPGBackupClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPGBackupClient) EXPECT() *MockPGBackupClientMockRecorder {
	return m.recorder
}

// Backup mocks base method.
func (m *MockPGBackupClient) Backup(ctx context.Context, kubeContext, namespace, stateDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", ctx, kubeContext, namespace, stateDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Backup indicates an expected call of Backup.
func (mr *MockPGBackupClientMockRecorder) Backup(ctx, kubeContext, namespace, stateDir any) *MockPGBackupClientBackupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockPGBackupClient)(nil).Backup), ctx, kubeContext, namespace, stateDir)
	return &MockPGBackupClientBackupCall{Call: call}
}

// MockPGBackupClientBackupCall wrap *gomock.Call
type MockPGBackupClientBackupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPGBackupClientBackupCall) Return(arg0 error) *MockPGBackupClientBackupCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPGBackupClientBackupCall) Do(f func(context.Context, string, string, string) error) *MockPGBackupClientBackupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPGBackupClientBackupCall) DoAndReturn(f func(context.Context, string, string, string) error) *MockPGBackupClientBackupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
