# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
---
name: Install Flux CLI and Source Controller
description: Installs Flux CLI and Source Controller.
inputs:
  version:
    description: Flux version to install
    required: false
    default: 2.6.4
runs:
  using: composite
  steps:
    - name: Install Flux CLI
      uses: fluxcd/flux2/action@dd233c4fadef306a62b7893204f8e3817fecc2b2 # v2.9.5
      with:
        version: ${{ inputs.version }}

    - name: Install Flux Source Controller
      shell: bash
      run: |
        .github/actions/install-flux/install-flux.sh "${INPUT_VERSION}"
      env:
        INPUT_VERSION: ${{ inputs.version }}
