# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
---
name: Install Flux CLI and Source Controller
description: Installs Flux CLI and Source Controller.
inputs:
  version:
    description: Flux version to install
    required: false
    default: 2.6.4
runs:
  using: composite
  steps:
    - name: Install Flux CLI
      uses: fluxcd/flux2/action@04acaec6161ac4fb1a82ffafa88901c03271d34f # v2.8.6
      with:
        version: ${{ inputs.version }}

    - name: Install Flux Source Controller
      shell: bash
      run: |
        .github/actions/install-flux/install-flux.sh ${{ inputs.version }}
