//go:build go1.18
// +build go1.18

// Licensed under the Apache License, Version 2.0 . See LICENSE in the repository root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package v20220315privatepreview

import "encoding/json"

func unmarshalDaprPubSubBrokerPropertiesClassification(rawMsg json.RawMessage) (DaprPubSubBrokerPropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b DaprPubSubBrokerPropertiesClassification
	switch m["mode"] {
	case "recipe":
		b = &RecipeDaprPubSubProperties{}
	case "resource":
		b = &ResourceDaprPubSubProperties{}
	case "values":
		b = &ValuesDaprPubSubProperties{}
	default:
		b = &DaprPubSubBrokerProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalDaprSecretStorePropertiesClassification(rawMsg json.RawMessage) (DaprSecretStorePropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b DaprSecretStorePropertiesClassification
	switch m["mode"] {
	case "recipe":
		b = &RecipeDaprSecretStoreProperties{}
	case "values":
		b = &ValuesDaprSecretStoreProperties{}
	default:
		b = &DaprSecretStoreProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalDaprStateStorePropertiesClassification(rawMsg json.RawMessage) (DaprStateStorePropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b DaprStateStorePropertiesClassification
	switch m["mode"] {
	case "recipe":
		b = &RecipeDaprStateStoreProperties{}
	case "resource":
		b = &ResourceDaprStateStoreProperties{}
	case "values":
		b = &ValuesDaprStateStoreProperties{}
	default:
		b = &DaprStateStoreProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalMongoDatabasePropertiesClassification(rawMsg json.RawMessage) (MongoDatabasePropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b MongoDatabasePropertiesClassification
	switch m["mode"] {
	case "recipe":
		b = &RecipeMongoDatabaseProperties{}
	case "resource":
		b = &ResourceMongoDatabaseProperties{}
	case "values":
		b = &ValuesMongoDatabaseProperties{}
	default:
		b = &MongoDatabaseProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalRabbitMQMessageQueuePropertiesClassification(rawMsg json.RawMessage) (RabbitMQMessageQueuePropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b RabbitMQMessageQueuePropertiesClassification
	switch m["mode"] {
	case "recipe":
		b = &RecipeRabbitMQMessageQueueProperties{}
	case "values":
		b = &ValuesRabbitMQMessageQueueProperties{}
	default:
		b = &RabbitMQMessageQueueProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalRedisCachePropertiesClassification(rawMsg json.RawMessage) (RedisCachePropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b RedisCachePropertiesClassification
	switch m["mode"] {
	case "recipe":
		b = &RecipeRedisCacheProperties{}
	case "resource":
		b = &ResourceRedisCacheProperties{}
	case "values":
		b = &ValuesRedisCacheProperties{}
	default:
		b = &RedisCacheProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalSQLDatabasePropertiesClassification(rawMsg json.RawMessage) (SQLDatabasePropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b SQLDatabasePropertiesClassification
	switch m["mode"] {
	case "recipe":
		b = &RecipeSQLDatabaseProperties{}
	case "resource":
		b = &ResourceSQLDatabaseProperties{}
	case "values":
		b = &ValuesSQLDatabaseProperties{}
	default:
		b = &SQLDatabaseProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

