//go:build go1.18
// +build go1.18

// Licensed under the Apache License, Version 2.0 . See LICENSE in the repository root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package v20220315privatepreview

// DaprPubSubBrokerClientCreateResponse contains the response from method DaprPubSubBrokerClient.Create.
type DaprPubSubBrokerClientCreateResponse struct {
	DaprPubSubBrokerResource
}

// DaprPubSubBrokerClientDeleteResponse contains the response from method DaprPubSubBrokerClient.Delete.
type DaprPubSubBrokerClientDeleteResponse struct {
	// placeholder for future response values
}

// DaprPubSubBrokerClientGetResponse contains the response from method DaprPubSubBrokerClient.Get.
type DaprPubSubBrokerClientGetResponse struct {
	DaprPubSubBrokerResource
}

// DaprPubSubBrokerClientListByScopeResponse contains the response from method DaprPubSubBrokerClient.ListByScope.
type DaprPubSubBrokerClientListByScopeResponse struct {
	DaprPubSubBrokerResourceListResult
}

// DaprPubSubBrokerClientUpdateResponse contains the response from method DaprPubSubBrokerClient.Update.
type DaprPubSubBrokerClientUpdateResponse struct {
	DaprPubSubBrokerResource
}

// DaprSecretStoresClientCreateResponse contains the response from method DaprSecretStoresClient.Create.
type DaprSecretStoresClientCreateResponse struct {
	DaprSecretStoreResource
}

// DaprSecretStoresClientDeleteResponse contains the response from method DaprSecretStoresClient.Delete.
type DaprSecretStoresClientDeleteResponse struct {
	// placeholder for future response values
}

// DaprSecretStoresClientGetResponse contains the response from method DaprSecretStoresClient.Get.
type DaprSecretStoresClientGetResponse struct {
	DaprSecretStoreResource
}

// DaprSecretStoresClientListByScopeResponse contains the response from method DaprSecretStoresClient.ListByScope.
type DaprSecretStoresClientListByScopeResponse struct {
	DaprSecretStoreResourceListResult
}

// DaprSecretStoresClientUpdateResponse contains the response from method DaprSecretStoresClient.Update.
type DaprSecretStoresClientUpdateResponse struct {
	DaprSecretStoreResource
}

// DaprStateStoreClientCreateResponse contains the response from method DaprStateStoreClient.Create.
type DaprStateStoreClientCreateResponse struct {
	DaprStateStoreResource
}

// DaprStateStoreClientDeleteResponse contains the response from method DaprStateStoreClient.Delete.
type DaprStateStoreClientDeleteResponse struct {
	// placeholder for future response values
}

// DaprStateStoreClientGetResponse contains the response from method DaprStateStoreClient.Get.
type DaprStateStoreClientGetResponse struct {
	DaprStateStoreResource
}

// DaprStateStoreClientListByScopeResponse contains the response from method DaprStateStoreClient.ListByScope.
type DaprStateStoreClientListByScopeResponse struct {
	DaprStateStoreResourceListResult
}

// DaprStateStoreClientUpdateResponse contains the response from method DaprStateStoreClient.Update.
type DaprStateStoreClientUpdateResponse struct {
	DaprStateStoreResource
}

// ExtendersClientCreateOrUpdateResponse contains the response from method ExtendersClient.CreateOrUpdate.
type ExtendersClientCreateOrUpdateResponse struct {
	ExtenderResource
}

// ExtendersClientDeleteResponse contains the response from method ExtendersClient.Delete.
type ExtendersClientDeleteResponse struct {
	// placeholder for future response values
}

// ExtendersClientGetResponse contains the response from method ExtendersClient.Get.
type ExtendersClientGetResponse struct {
	ExtenderResource
}

// ExtendersClientListByRootScopeResponse contains the response from method ExtendersClient.ListByRootScope.
type ExtendersClientListByRootScopeResponse struct {
	ExtenderList
}

// ExtendersClientListSecretsResponse contains the response from method ExtendersClient.ListSecrets.
type ExtendersClientListSecretsResponse struct {
	// The secret values for the given Extender resource
	Value map[string]interface{}
}

// MongoDatabasesClientCreateResponse contains the response from method MongoDatabasesClient.Create.
type MongoDatabasesClientCreateResponse struct {
	MongoDatabaseResource
}

// MongoDatabasesClientDeleteResponse contains the response from method MongoDatabasesClient.Delete.
type MongoDatabasesClientDeleteResponse struct {
	// placeholder for future response values
}

// MongoDatabasesClientGetResponse contains the response from method MongoDatabasesClient.Get.
type MongoDatabasesClientGetResponse struct {
	MongoDatabaseResource
}

// MongoDatabasesClientListByScopeResponse contains the response from method MongoDatabasesClient.ListByScope.
type MongoDatabasesClientListByScopeResponse struct {
	MongoDatabaseResourceListResult
}

// MongoDatabasesClientListSecretsResponse contains the response from method MongoDatabasesClient.ListSecrets.
type MongoDatabasesClientListSecretsResponse struct {
	MongoDatabaseListSecretsResult
}

// MongoDatabasesClientUpdateResponse contains the response from method MongoDatabasesClient.Update.
type MongoDatabasesClientUpdateResponse struct {
	MongoDatabaseResource
}

// OperationsClientListResponse contains the response from method OperationsClient.List.
type OperationsClientListResponse struct {
	OperationListResult
}

// RabbitMqMessageQueuesClientCreateResponse contains the response from method RabbitMqMessageQueuesClient.Create.
type RabbitMqMessageQueuesClientCreateResponse struct {
	RabbitMQMessageQueueResource
}

// RabbitMqMessageQueuesClientDeleteResponse contains the response from method RabbitMqMessageQueuesClient.Delete.
type RabbitMqMessageQueuesClientDeleteResponse struct {
	// placeholder for future response values
}

// RabbitMqMessageQueuesClientGetResponse contains the response from method RabbitMqMessageQueuesClient.Get.
type RabbitMqMessageQueuesClientGetResponse struct {
	RabbitMQMessageQueueResource
}

// RabbitMqMessageQueuesClientListByScopeResponse contains the response from method RabbitMqMessageQueuesClient.ListByScope.
type RabbitMqMessageQueuesClientListByScopeResponse struct {
	RabbitMQMessageQueueResourceListResult
}

// RabbitMqMessageQueuesClientListSecretsResponse contains the response from method RabbitMqMessageQueuesClient.ListSecrets.
type RabbitMqMessageQueuesClientListSecretsResponse struct {
	RabbitMQListSecretsResult
}

// RabbitMqMessageQueuesClientUpdateResponse contains the response from method RabbitMqMessageQueuesClient.Update.
type RabbitMqMessageQueuesClientUpdateResponse struct {
	RabbitMQMessageQueueResource
}

// RedisCachesClientCreateResponse contains the response from method RedisCachesClient.Create.
type RedisCachesClientCreateResponse struct {
	RedisCacheResource
}

// RedisCachesClientDeleteResponse contains the response from method RedisCachesClient.Delete.
type RedisCachesClientDeleteResponse struct {
	// placeholder for future response values
}

// RedisCachesClientGetResponse contains the response from method RedisCachesClient.Get.
type RedisCachesClientGetResponse struct {
	RedisCacheResource
}

// RedisCachesClientListByScopeResponse contains the response from method RedisCachesClient.ListByScope.
type RedisCachesClientListByScopeResponse struct {
	RedisCacheResourceListResult
}

// RedisCachesClientListSecretsResponse contains the response from method RedisCachesClient.ListSecrets.
type RedisCachesClientListSecretsResponse struct {
	RedisCacheListSecretsResult
}

// RedisCachesClientUpdateResponse contains the response from method RedisCachesClient.Update.
type RedisCachesClientUpdateResponse struct {
	RedisCacheResource
}

// SQLDatabasesClientCreateResponse contains the response from method SQLDatabasesClient.Create.
type SQLDatabasesClientCreateResponse struct {
	SQLDatabaseResource
}

// SQLDatabasesClientDeleteResponse contains the response from method SQLDatabasesClient.Delete.
type SQLDatabasesClientDeleteResponse struct {
	// placeholder for future response values
}

// SQLDatabasesClientGetResponse contains the response from method SQLDatabasesClient.Get.
type SQLDatabasesClientGetResponse struct {
	SQLDatabaseResource
}

// SQLDatabasesClientListByScopeResponse contains the response from method SQLDatabasesClient.ListByScope.
type SQLDatabasesClientListByScopeResponse struct {
	SQLDatabaseResourceListResult
}

// SQLDatabasesClientListSecretsResponse contains the response from method SQLDatabasesClient.ListSecrets.
type SQLDatabasesClientListSecretsResponse struct {
	SQLDatabaseListSecretsResult
}

// SQLDatabasesClientUpdateResponse contains the response from method SQLDatabasesClient.Update.
type SQLDatabasesClientUpdateResponse struct {
	SQLDatabaseResource
}

