// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

package list

import (
	"fmt"
	"io"

	"github.com/charmbracelet/bubbles/list"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

const listHeight = 14

const defaultWidth = 400

var (
	titleStyle        = lipgloss.NewStyle().PaddingLeft(2)
	itemStyle         = lipgloss.NewStyle().PaddingLeft(4)
	selectedItemStyle = lipgloss.NewStyle().PaddingLeft(2).Foreground(lipgloss.Color("170"))
	quitTextStyle     = lipgloss.NewStyle().Margin(1, 0, 2, 4)
)

type item string

//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	The previous function is returning a string representation of the item that was passed in as an argument.
//
// </AiDoc: End of OpenAI comments>
func (i item) FilterValue() string { return string(i) }

type itemHandler struct{}

// Height handles height of the prompt.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is returning an integer value of 1, which is the height of the itemHandler.
//
// </AiDoc: End of OpenAI comments>
func (d itemHandler) Height() int {
	return 1
}

// Spacing handles spacing of the prompt.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is part of an itemHandler struct and returns an integer value of 0.
//
// </AiDoc: End of OpenAI comments>
func (d itemHandler) Spacing() int {
	return 0
}

// Update handles the updates to model.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is part of an itemHandler struct and is used to update a list model. It takes in a message and a list 
//	model as parameters and returns a command.
//
// </AiDoc: End of OpenAI comments>
func (d itemHandler) Update(msg tea.Msg, m *list.Model) tea.Cmd {
	return nil
}

// Render renders the prompt for user.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is used to render a list item in a list. It takes in a writer, a model, an index, and a list item as 
//	parameters. It checks if the list item is of the correct type, and if it is, it formats the item as a string with the 
//	index number and the item itself. It then uses a style to render the item, and if the index is equal to the model's 
//	index, it uses a different style to render the item. Finally, it prints the formatted item to the writer.
//
// </AiDoc: End of OpenAI comments>
func (d itemHandler) Render(w io.Writer, m list.Model, index int, listItem list.Item) {
	i, ok := listItem.(item)
	if !ok {
		return
	}

	str := fmt.Sprintf("%d. %s", index+1, i)

	fn := itemStyle.Render
	if index == m.Index() {
		fn = func(s string) string {
			return selectedItemStyle.Render("> " + s)
		}
	}

	fmt.Fprint(w, fn(str))
}

// NewListModel returns a list model for bubble tea prompt.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function creates a new ListModel object with a list of choices and a prompt message. It creates a list of items 
//	from the given choices, sets the title of the list to the prompt message, enables filtering, and sets the style of the 
//	title.
//
// </AiDoc: End of OpenAI comments>
func NewListModel(choices []string, promptMsg string) ListModel {
	items := make([]list.Item, len(choices))
	for i, choice := range choices {
		items[i] = item(choice)
	}

	l := list.New(items, itemHandler{}, defaultWidth, listHeight)
	l.Title = promptMsg
	l.SetShowStatusBar(false)
	l.SetFilteringEnabled(true)
	l.Styles.Title = titleStyle

	return ListModel{
		List: l,
	}
}

// ListMode represents the bubble tea model to use for user input
type ListModel struct {
	List     list.Model
	Choice   string
	Quitting bool
}

// Init used for creating an inital tea command if needed.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function initializes the ListModel, which is a type of model used in the Tea framework.
//
// </AiDoc: End of OpenAI comments>
func (m ListModel) Init() tea.Cmd {
	return nil
}

// Update handles the updates from user input.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is updating the ListModel based on the message that is passed in. Depending on the type of message, it 
//	will either quit the program, or select an item from the list.
//
// </AiDoc: End of OpenAI comments>
func (m ListModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {

	case tea.KeyMsg:
		switch keypress := msg.String(); keypress {
		case "ctrl+c", "esc", "q":
			m.Quitting = true
			return m, tea.Quit
		case "enter":
			if m.List.FilterState() != list.Filtering {
				i, ok := m.List.SelectedItem().(item)
				if ok {
					m.Choice = string(i)
				}
				return m, tea.Quit
			}
		}
	}

	var cmd tea.Cmd
	m.List, cmd = m.List.Update(msg)
	return m, cmd
}

// View renders the view after user selection.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is used to display a list of choices to the user. It takes in a ListModel object which contains a List 
//	object and a Choice string. If the Choice string is not empty, it will render the title of the list and the Choice 
//	string. Otherwise, it will render the list of choices.
//
// </AiDoc: End of OpenAI comments>
func (m ListModel) View() string {
	if m.Choice != "" {
		return quitTextStyle.Render(fmt.Sprintf("%s: %s", m.List.Title, m.Choice))
	}

	return "\n" + m.List.View()
}
