//go:build go1.18
// +build go1.18

// Licensed under the Apache License, Version 2.0 . See LICENSE in the repository root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v20231001preview

// OperationsClientListOptions contains the optional parameters for the OperationsClient.NewListPager method.
type OperationsClientListOptions struct {
	// placeholder for future optional parameters
}

// PubSubBrokersClientBeginCreateOrUpdateOptions contains the optional parameters for the PubSubBrokersClient.BeginCreateOrUpdate
// method.
type PubSubBrokersClientBeginCreateOrUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// PubSubBrokersClientBeginDeleteOptions contains the optional parameters for the PubSubBrokersClient.BeginDelete method.
type PubSubBrokersClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// PubSubBrokersClientBeginUpdateOptions contains the optional parameters for the PubSubBrokersClient.BeginUpdate method.
type PubSubBrokersClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// PubSubBrokersClientGetOptions contains the optional parameters for the PubSubBrokersClient.Get method.
type PubSubBrokersClientGetOptions struct {
	// placeholder for future optional parameters
}

// PubSubBrokersClientListByScopeOptions contains the optional parameters for the PubSubBrokersClient.NewListByScopePager
// method.
type PubSubBrokersClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// SecretStoresClientBeginCreateOrUpdateOptions contains the optional parameters for the SecretStoresClient.BeginCreateOrUpdate
// method.
type SecretStoresClientBeginCreateOrUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// SecretStoresClientBeginDeleteOptions contains the optional parameters for the SecretStoresClient.BeginDelete method.
type SecretStoresClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// SecretStoresClientBeginUpdateOptions contains the optional parameters for the SecretStoresClient.BeginUpdate method.
type SecretStoresClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// SecretStoresClientGetOptions contains the optional parameters for the SecretStoresClient.Get method.
type SecretStoresClientGetOptions struct {
	// placeholder for future optional parameters
}

// SecretStoresClientListByScopeOptions contains the optional parameters for the SecretStoresClient.NewListByScopePager method.
type SecretStoresClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// StateStoresClientBeginCreateOrUpdateOptions contains the optional parameters for the StateStoresClient.BeginCreateOrUpdate
// method.
type StateStoresClientBeginCreateOrUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// StateStoresClientBeginDeleteOptions contains the optional parameters for the StateStoresClient.BeginDelete method.
type StateStoresClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// StateStoresClientBeginUpdateOptions contains the optional parameters for the StateStoresClient.BeginUpdate method.
type StateStoresClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// StateStoresClientGetOptions contains the optional parameters for the StateStoresClient.Get method.
type StateStoresClientGetOptions struct {
	// placeholder for future optional parameters
}

// StateStoresClientListByScopeOptions contains the optional parameters for the StateStoresClient.NewListByScopePager method.
type StateStoresClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

