FROM debian:stable-slim

ARG TARGETPLATFORM

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  ca-certificates \
  openssl \
  && update-ca-certificates \
  && rm -rf /var/lib/apt/lists/*

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

RUN useradd -m -s /bin/bash controlleruser && \
  mkdir -p /home/controlleruser && \
  chown -R controlleruser:controlleruser /home/controlleruser

COPY ${TARGETPLATFORM}/controller /controller

USER controlleruser

WORKDIR /

ENTRYPOINT ["/controller"]
