@startuml


' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesApi.puml
!includeurl KubernetesPuml/OSS/KubernetesSecret.puml
!includeurl KubernetesPuml/OSS/KubernetesPod.puml

' Azure
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist

' !includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml

!includeurl AzurePuml/Management/AzureManagementPortal.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml

skinparam maxMessageSize 150
!define Rel_(e_alias1, e_alias2, e_label, e_direction="") e_alias1 e_direction e_alias2 : "<size:16><b>[e_label]</size>"
' !define Rel_(e_alias1, e_alias2, e_label, e_techn, e_direction="") e_alias1 e_direction e_alias2 : "e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//"

actor "User" as user
rectangle "Radius CLI" as rad

!$a = "rad env init dev \
~--provider-azure \
~--provider-azure-subscription={{subscription_id}} \
~--provider-azure-resource-group={{rg_id}} \
~--provider-azure-client-id={{appId}} \
~--provider-azure-client-secret={{password}} \
~--provider-azure-tenant-id={{tenant}}"

Rel_R(user, rad ,$a)




'Kubernetes Components
Cluster_Boundary(cluster, "Radius Environment\n Standalone") {
    KubernetesApi(k8sAPI, "Kubernetes API", "")
    Namespace_Boundary(ns, "radius-system") {
        Service_Boundary(de, "Deployment Engine") {
            KubernetesSecret(s, "radius-rp", "")
            KubernetesPod(depod, "", "")
        }
    }
}

AzureManagementPortal(arm, "ARM", "")
AzureActiveDirectory(aad, "AAD", "")

Rel(rad, k8sAPI, "deploy(helm_chart)")
Rel_Neighbor(s, depod, "secret is loaded to env")
Rel_D(depod, arm, "create(auth_token, subscription_id, rg_id, sazure_resource)")
Rel_R(depod, aad,  "get_auth_token(client_id, tenant_id, client_secret)")
Rel(k8sAPI, ns, "deploy radius components")


@enduml