@startuml
skinparam responseMessageBelowArrow true
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist

title Figure 1: User creates a Service Principal Name (SPN)

actor User as user
participant "Azure CLI" as az

user -> az: ""az ad sp create-for-rbac -n radius-foobar""
az --> user:

note over user #LightGray
    <code>
    {
    "appId": "00000000-0000-0000-0000-000000000000",
    "displayName": "radius-foobar",
    "password": "superSecretString",
    "tenant": "00000000-0000-0000-0000-000000000000"
    }
    </code>
end note

@enduml