// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/project-radius/radius/pkg/health/db (interfaces: RadHealthDB)

// Package db is a generated GoMock package.
package db

import (
	gomock "github.com/golang/mock/gomock"
)

// MockRadHealthDB is a mock of RadHealthDB interface.
type MockRadHealthDB struct {
	ctrl     *gomock.Controller
	recorder *MockRadHealthDBMockRecorder
}

// MockRadHealthDBMockRecorder is the mock recorder for MockRadHealthDB.
type MockRadHealthDBMockRecorder struct {
	mock *MockRadHealthDB
}

// NewMockRadHealthDB creates a new mock instance.
func NewMockRadHealthDB(ctrl *gomock.Controller) *MockRadHealthDB {
	mock := &MockRadHealthDB{ctrl: ctrl}
	mock.recorder = &MockRadHealthDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRadHealthDB) EXPECT() *MockRadHealthDBMockRecorder {
	return m.recorder
}
