{
 "title": "Cluster Health",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Idle Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{container!=\"POD\",container!=\"\"} - on (namespace,pod,container) avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\"})) * -1 >0 ) / (1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[30m]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count by (namespace)(sum by (namespace,pod,container)(kube_pod_container_info{container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unstable Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(changes(kube_node_status_condition{status=\"true\",condition=\"Ready\"}[15m])) by (node) > 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Persistent Volume Claim",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Pending\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Unknown|Failed\"})[15m:1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Crash Looping Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[15m]) > 3",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}