{
 "title": "Core RP & Link RP",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DATA_SOURCE", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Usage (Last 5 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"appcore-rp\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Throttling per Second (last 5 mins)",
   "type": "timeseries",
   "description": "When a container exceeds its CPU limits, OS will throttle the container and record the amount of time it was throttled.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{container=\"appcore-rp\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage (IEC Bytes)",
   "type": "timeseries",
   "description": "This is an estimate of how much memory cannot be evicted.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"appcore-rp\"}) by (container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Percentage)",
   "type": "timeseries",
   "description": "Go heap size (allocated objects in use plus allocated objects not in use anymore but not yet garbage-collected).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"appcore-rp\"}) by (container) / ignoring (container) group_left sum(machine_memory_bytes{}) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container=\"appcore-rp\"}[5m])) by (container,device)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container=\"appcore-rp\"}[5m])) by (container,device)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container=\"appcore-rp\"}[5m])) by (container,device) + sum(rate(container_fs_reads_bytes_total{container=\"appcore-rp\"}[5m])) by (container,device)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Server Side Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "Availability",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - sum(rate(http_server_duration_count{http_status_code=~\"[45]..\"}[5m])) / ignoring (http_method, http_status_code) group_left sum(rate(http_server_duration_count[5m]))",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Incoming Requests per Second (Last 5 Minutes)",
   "type": "timeseries",
   "description": "Per-second rate of HTTP requests as averaged over a time window of 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count[5m]))",
     "legendFormat": "Incoming Requests"
    }
   ]
  },
  {
   "title": "Total Error Ratio (Last 5 Minutes)",
   "type": "timeseries",
   "description": "Total Error Ratio (Last 5 Minutes)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{http_status_code=~\"[45]..\"}[5m])) / ignoring (http_method, http_status_code) group_left sum(rate(http_server_duration_count[5m])) * 100",
     "legendFormat": "Error Ratio"
    }
   ]
  },
  {
   "title": "Response Time (p99, p75, p50)",
   "type": "timeseries",
   "description": "Response Time (p99, p75, p50)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(http_server_duration_bucket[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le)(rate(http_server_duration_bucket[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(http_server_duration_bucket[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Response Time by HTTP Method",
   "type": "timeseries",
   "description": "Response Time by HTTP Method",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_,http_method)(rate(http_server_duration_count{control_plane=\"appcore-rp\"}[5m]))",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Response Time by Status Code",
   "type": "timeseries",
   "description": "P99 Response Time by Status Code",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_status_code)(rate(http_server_duration_count{control_plane=\"appcore-rp\"}[5m]))",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  { "title": "Operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Incoming Operations per Second (Last 5 Minutes)",
   "type": "timeseries",
   "description": "Number of incoming async operation requests per second over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(asyncoperation_queued_operation_total{control_plane=\"appcore-rp\", resource_type!=\"\"}[5m]))",
     "legendFormat": "Incoming Operations"
    }
   ]
  },
  {
   "title": "Failed Operations",
   "type": "timeseries",
   "description": "Number of failed operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(rate(asyncoperation_operation_total{control_plane=\"appcore-rp\", resource_type!=\"\", operation_state=\"failed\"}[5m]))",
     "legendFormat": "Failed Operations"
    }
   ]
  },
  {
   "title": "Operation Duration (p99, p75, p50)",
   "type": "timeseries",
   "description": "Average Async Operation Duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(asyncoperation_duration_bucket{control_plane=\"appcore-rp\", resource_type!=\"\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le)(rate(asyncoperation_duration_bucket{control_plane=\"appcore-rp\", resource_type!=\"\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(asyncoperation_duration_bucket{control_plane=\"appcore-rp\", resource_type!=\"\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Operation Duration by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, operation_type)(rate(asyncoperation_duration_bucket[5m])))",
     "legendFormat": "{{operation_type}}"
    }
   ]
  }
 ]
}