{
 "title": "Radius Resource Provider",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DATA_SOURCE", "label": "Data Source", "query": "prometheus" },
   { "name": "servicename", "query": "applications-rp" }
  ]
 },
 "panels": [
  { "title": "Runtime instrumentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU Usage",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{container=\"$servicename\"}[$__rate_interval])) ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "GC execution count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (control_plane) (increase(process_runtime_go_gc_count_total{control_plane=\"$servicename\"}[$__rate_interval]))",
     "legendFormat": "{{control_plane}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "This is an estimate of how much memory cannot be evicted.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (control_plane) (process_runtime_go_mem_heap_sys_bytes{control_plane=\"$servicename\"})",
     "legendFormat": "HeapMem"
    },
    {
     "expr": "sum by (container) (container_memory_working_set_bytes{container=~\"^$servicename\"})",
     "legendFormat": "WorkingSetMem"
    }
   ]
  },
  {
   "title": "Number of Go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum  by (control_plane) (process_runtime_go_goroutines{control_plane=\"$servicename\"})",
     "legendFormat": "{{control_plane}}"
    }
   ]
  },
  { "title": "Frontend API server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(runtime_uptime_milliseconds_total{control_plane=\"$servicename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{http_status_code!~\"[5]..\", control_plane=\"$servicename\"}[$__rate_interval])) / sum(rate(http_server_duration_count{control_plane=\"$servicename\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Endpoint Availability",
   "type": "timeseries",
   "description": "HTTP Endpoint Availability",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{http_status_code!~\"[5]..\", control_plane=\"$servicename\"}[$__rate_interval])) / sum(rate(http_server_duration_count{control_plane=\"$servicename\"}[$__rate_interval])) * 100",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Incoming requests per seconds",
   "type": "timeseries",
   "description": "Per-second rate of HTTP requests as averaged over a time window of the rate interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{control_plane=\"$servicename\"}[$__rate_interval]))",
     "legendFormat": "Incoming Requests"
    }
   ]
  },
  {
   "title": "Incoming request by status code",
   "type": "timeseries",
   "description": "Incoming request by status code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (increase(http_server_duration_count{control_plane=\"$servicename\"}[$__rate_interval]))",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Response Time (p99, p75, p50)",
   "type": "timeseries",
   "description": "Response Time (p99, p75, p50)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(http_server_duration_bucket{control_plane=\"$servicename\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le)(rate(http_server_duration_bucket{control_plane=\"$servicename\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(http_server_duration_bucket{control_plane=\"$servicename\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Asynchronous operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total asynchronous operations",
   "type": "timeseries",
   "description": "Number of successful and failure requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (operation_state) (increase(asyncoperation_operation_total{control_plane=\"$servicename\", resource_type!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total operations per resource type",
   "type": "timeseries",
   "description": "Number of successful and failure requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(resource_type, operation_type) (increase(asyncoperation_operation_total{control_plane=\"$servicename\", resource_type!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{operation_type}}-{{ resource_type }}"
    }
   ]
  },
  {
   "title": "Job execution time (p99, p75, p50)",
   "type": "timeseries",
   "description": "Average Async Operation Duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(asyncoperation_duration_bucket{control_plane=\"$servicename\", resource_type!=\"\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le)(rate(asyncoperation_duration_bucket{control_plane=\"applications-rp\", resource_type!=\"\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(asyncoperation_duration_bucket{control_plane=\"applications-rp\", resource_type!=\"\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Job execution time (p99) per operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, operation_type, resource_type)(rate(asyncoperation_duration_bucket{control_plane=\"$servicename\"}[$__rate_interval])))",
     "legendFormat": "{{resource_type}} - {{operation_type}}"
    }
   ]
  }
 ]
}