{
 "title": "Radius Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DATA_SOURCE", "query": "prometheus" },
   {
    "name": "servicenames",
    "query": "^bicep-de|^de|^ucp|^applications-rp"
   },
   { "name": "de_servicename", "query": "^de|^bicep-de" }
  ]
 },
 "panels": [
  { "title": "Radius Runtime Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (control_plane) (runtime_uptime_milliseconds_total{control_plane=~\"$servicenames\"})",
     "legendFormat": "{{control_plane}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU Usage",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{container=~\"$servicenames\"}[$__rate_interval])) ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage (working set)",
   "type": "timeseries",
   "description": "The amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory. Working set is <= \"usage\".",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_working_set_bytes{container=~\"$servicenames\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "This is an estimate of how much memory cannot be evicted.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (control_plane) (process_runtime_go_mem_heap_sys_bytes{control_plane=~\"$servicenames\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (control_plane) (process_runtime_go_goroutines{control_plane=~\"$servicenames\"})",
     "legendFormat": "{{control_plane}}"
    }
   ]
  },
  {
   "title": "Go GC execution count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (control_plane) (increase(process_runtime_go_gc_count_total{control_plane=~\"$servicenames\"}[$__rate_interval]))",
     "legendFormat": "{{control_plane}}"
    }
   ]
  },
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{http_status_code!~\"[5]..\", control_plane=~\"ucp\"}[$__rate_interval])) / sum(rate(http_server_duration_count{control_plane=\"ucp\"}[$__rate_interval])) * 100",
     "legendFormat": "ucp"
    },
    {
     "expr": "sum(rate(http_server_duration_count{http_status_code!~\"[5]..\", control_plane=~\"applications-rp\"}[$__rate_interval])) / sum(rate(http_server_duration_count{control_plane=\"applications-rp\"}[$__rate_interval])) * 100",
     "legendFormat": "applications-rp"
    },
    {
     "expr": "sum(rate(http_server_duration_ms_count{http_status_code!~\"[5]..\", control_plane=~\"de\"}[$__rate_interval])) / sum(rate(http_server_duration_ms_count{control_plane=\"de\"}[$__rate_interval])) * 100",
     "legendFormat": "de"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{http_status_code!~\"[5]..\", control_plane=~\"ucp\"}[$__rate_interval])) / sum(rate(http_server_duration_count{control_plane=\"ucp\"}[$__rate_interval])) * 100",
     "legendFormat": "ucp"
    },
    {
     "expr": "sum(rate(http_server_duration_count{http_status_code!~\"[5]..\", control_plane=~\"applications-rp\"}[$__rate_interval])) / sum(rate(http_server_duration_count{control_plane=\"applications-rp\"}[$__rate_interval])) * 100",
     "legendFormat": "applications-rp"
    },
    {
     "expr": "sum(rate(http_server_duration_ms_count{http_status_code!~\"[5]..\", control_plane=~\"de\"}[$__rate_interval])) / sum(rate(http_server_duration_ms_count{control_plane=\"de\"}[$__rate_interval])) * 100",
     "legendFormat": "de"
    }
   ]
  },
  {
   "title": "Incoming requests",
   "type": "timeseries",
   "description": "Incoming requests",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(control_plane) (increase(http_server_duration_count{control_plane=~\"$servicenames\"}[$__rate_interval]))",
     "legendFormat": "{{control_plane}}"
    },
    {
     "expr": "sum by(control_plane) (increase(http_server_duration_ms_count{control_plane=~\"de\"}[$__rate_interval]))",
     "legendFormat": "{{control_plane}}"
    }
   ]
  },
  { "title": "Deployment Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU Usage",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{container=~\"$de_servicename\"}[$__rate_interval])) ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage (working set)",
   "type": "timeseries",
   "description": "The amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory. Working set is <= \"usage\".",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_working_set_bytes{container=~\"$de_servicename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": ".NET GC execution counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (control_plane) (increase(process_runtime_dotnet_gc_collections_count{control_plane=~\"$de_servicename\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of thread pool threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (control_plane) (process_runtime_dotnet_thread_pool_threads_count{control_plane=~\"$de_servicename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming requests per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(control_plane) (rate(http_server_duration_ms_count{control_plane=~\"$de_servicename\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming requests by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (http_status_code) (increase(http_server_duration_ms_count{control_plane=~\"$de_servicename\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}