// Licensed under the Apache License, Version 2.0 . See LICENSE in the repository root for license information.
// Code generated by @autorest/go. DO NOT EDIT.

package v20250801preview

const (
	version20250801Preview string = "2025-08-01-preview"
)

// ActionType - Extensible enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs.
type ActionType string

const (
	// ActionTypeInternal - Actions are for internal-only APIs.
	ActionTypeInternal ActionType = "Internal"
)

// PossibleActionTypeValues returns the possible values for the ActionType const type.
func PossibleActionTypeValues() []ActionType {
	return []ActionType{
		ActionTypeInternal,
	}
}

// BicepAuthenticationMethod - Supported authentication methods for private Bicep registries.
type BicepAuthenticationMethod string

const (
	// BicepAuthenticationMethodAwsIrsa - AWS IAM Roles for Service Accounts authentication.
	BicepAuthenticationMethodAwsIrsa BicepAuthenticationMethod = "AwsIrsa"
	// BicepAuthenticationMethodAzureWI - Azure Workload Identity authentication.
	BicepAuthenticationMethodAzureWI BicepAuthenticationMethod = "AzureWI"
	// BicepAuthenticationMethodBasicAuth - Username/password authentication.
	BicepAuthenticationMethodBasicAuth BicepAuthenticationMethod = "BasicAuth"
)

// PossibleBicepAuthenticationMethodValues returns the possible values for the BicepAuthenticationMethod const type.
func PossibleBicepAuthenticationMethodValues() []BicepAuthenticationMethod {
	return []BicepAuthenticationMethod{
		BicepAuthenticationMethodAwsIrsa,
		BicepAuthenticationMethodAzureWI,
		BicepAuthenticationMethodBasicAuth,
	}
}

// CreatedByType - The kind of entity that created the resource.
type CreatedByType string

const (
	// CreatedByTypeApplication - The entity was created by an application.
	CreatedByTypeApplication CreatedByType = "Application"
	// CreatedByTypeKey - The entity was created by a key.
	CreatedByTypeKey CreatedByType = "Key"
	// CreatedByTypeManagedIdentity - The entity was created by a managed identity.
	CreatedByTypeManagedIdentity CreatedByType = "ManagedIdentity"
	// CreatedByTypeUser - The entity was created by a user.
	CreatedByTypeUser CreatedByType = "User"
)

// PossibleCreatedByTypeValues returns the possible values for the CreatedByType const type.
func PossibleCreatedByTypeValues() []CreatedByType {
	return []CreatedByType{
		CreatedByTypeApplication,
		CreatedByTypeKey,
		CreatedByTypeManagedIdentity,
		CreatedByTypeUser,
	}
}

// Direction - The direction of a connection.
type Direction string

const (
	// DirectionInbound - The resource defining this connection accepts inbound connections from the resource specified by this
	// id.
	DirectionInbound Direction = "Inbound"
	// DirectionOutbound - The resource defining this connection makes an outbound connection resource specified by this id.
	DirectionOutbound Direction = "Outbound"
)

// PossibleDirectionValues returns the possible values for the Direction const type.
func PossibleDirectionValues() []Direction {
	return []Direction{
		DirectionInbound,
		DirectionOutbound,
	}
}

// IdentitySettingKind - IdentitySettingKind is the kind of supported external identity setting
type IdentitySettingKind string

const (
	// IdentitySettingKindAzureComWorkload - azure ad workload identity
	IdentitySettingKindAzureComWorkload IdentitySettingKind = "azure.com.workload"
	// IdentitySettingKindSystemAssigned - System assigned managed identity
	IdentitySettingKindSystemAssigned IdentitySettingKind = "systemAssigned"
	// IdentitySettingKindSystemAssignedUserAssigned - System assigned and user assigned managed identity
	IdentitySettingKindSystemAssignedUserAssigned IdentitySettingKind = "systemAssignedUserAssigned"
	// IdentitySettingKindUndefined - undefined identity
	IdentitySettingKindUndefined IdentitySettingKind = "undefined"
	// IdentitySettingKindUserAssigned - User assigned managed identity
	IdentitySettingKindUserAssigned IdentitySettingKind = "userAssigned"
)

// PossibleIdentitySettingKindValues returns the possible values for the IdentitySettingKind const type.
func PossibleIdentitySettingKindValues() []IdentitySettingKind {
	return []IdentitySettingKind{
		IdentitySettingKindAzureComWorkload,
		IdentitySettingKindSystemAssigned,
		IdentitySettingKindSystemAssignedUserAssigned,
		IdentitySettingKindUndefined,
		IdentitySettingKindUserAssigned,
	}
}

// Origin - The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default
// value is "user,system"
type Origin string

const (
	// OriginSystem - Indicates the operation is initiated by a system.
	OriginSystem Origin = "system"
	// OriginUser - Indicates the operation is initiated by a user.
	OriginUser Origin = "user"
	// OriginUserSystem - Indicates the operation is initiated by a user or system.
	OriginUserSystem Origin = "user,system"
)

// PossibleOriginValues returns the possible values for the Origin const type.
func PossibleOriginValues() []Origin {
	return []Origin{
		OriginSystem,
		OriginUser,
		OriginUserSystem,
	}
}

// ProvisioningState - Provisioning state of the resource at the time the operation was called
type ProvisioningState string

const (
	// ProvisioningStateAccepted - The resource create request has been accepted
	ProvisioningStateAccepted ProvisioningState = "Accepted"
	// ProvisioningStateCanceled - The resource provisioning has been canceled
	ProvisioningStateCanceled ProvisioningState = "Canceled"
	// ProvisioningStateCreating - The resource is being created
	ProvisioningStateCreating ProvisioningState = "Creating"
	// ProvisioningStateDeleting - The resource is being deleted
	ProvisioningStateDeleting ProvisioningState = "Deleting"
	// ProvisioningStateFailed - The resource provisioning has failed
	ProvisioningStateFailed ProvisioningState = "Failed"
	// ProvisioningStateProvisioning - The resource is being provisioned
	ProvisioningStateProvisioning ProvisioningState = "Provisioning"
	// ProvisioningStateSucceeded - The resource has been successfully provisioned
	ProvisioningStateSucceeded ProvisioningState = "Succeeded"
	// ProvisioningStateUpdating - The resource is being updated
	ProvisioningStateUpdating ProvisioningState = "Updating"
)

// PossibleProvisioningStateValues returns the possible values for the ProvisioningState const type.
func PossibleProvisioningStateValues() []ProvisioningState {
	return []ProvisioningState{
		ProvisioningStateAccepted,
		ProvisioningStateCanceled,
		ProvisioningStateCreating,
		ProvisioningStateDeleting,
		ProvisioningStateFailed,
		ProvisioningStateProvisioning,
		ProvisioningStateSucceeded,
		ProvisioningStateUpdating,
	}
}

// RecipeKind - The type of recipe
type RecipeKind string

const (
	// RecipeKindBicep - Bicep recipe
	RecipeKindBicep RecipeKind = "bicep"
	// RecipeKindTerraform - Terraform recipe
	RecipeKindTerraform RecipeKind = "terraform"
)

// PossibleRecipeKindValues returns the possible values for the RecipeKind const type.
func PossibleRecipeKindValues() []RecipeKind {
	return []RecipeKind{
		RecipeKindBicep,
		RecipeKindTerraform,
	}
}
