//go:build go1.18
// +build go1.18

// Licensed under the Apache License, Version 2.0 . See LICENSE in the repository root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package v20220901privatepreview

import "encoding/json"

func unmarshalAWSCredentialPropertiesClassification(rawMsg json.RawMessage) (AWSCredentialPropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b AWSCredentialPropertiesClassification
	switch m["kind"] {
	case "AccessKey":
		b = &AWSAccessKeyCredentialProperties{}
	default:
		b = &AWSCredentialProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalAzureCredentialPropertiesClassification(rawMsg json.RawMessage) (AzureCredentialPropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b AzureCredentialPropertiesClassification
	switch m["kind"] {
	case "ServicePrincipal":
		b = &AzureServicePrincipalProperties{}
	default:
		b = &AzureCredentialProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalCredentialStoragePropertiesClassification(rawMsg json.RawMessage) (CredentialStoragePropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b CredentialStoragePropertiesClassification
	switch m["kind"] {
	case "Internal":
		b = &InternalCredentialStorageProperties{}
	default:
		b = &CredentialStorageProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

