//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package v20220901privatepreview

import "encoding/json"

func unmarshalAwsCredentialPropertiesClassification(rawMsg json.RawMessage) (AwsCredentialPropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b AwsCredentialPropertiesClassification
	switch m["aws.com.iam"] {
	default:
		b = &AwsCredentialProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

func unmarshalAzureServicePrincipalPropertiesClassification(rawMsg json.RawMessage) (AzureServicePrincipalPropertiesClassification, error) {
	if rawMsg == nil {
		return nil, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b AzureServicePrincipalPropertiesClassification
	switch m["azure.com.serviceprincipal"] {
	default:
		b = &AzureServicePrincipalProperties{}
	}
	return b, json.Unmarshal(rawMsg, b)
}

