#!/usr/bin/env bash
set -eu

if [[ $# -ne 1 ]]
then
    echo "usage: delete-applications <resource group>"
    exit 1
fi

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

RESOURCE_GROUP_ID="$(az group show --name $1 --query id --output tsv)"
URI="$RESOURCE_GROUP_ID/providers/Microsoft.CustomProviders/resourceProviders/radius/Applications"
VERSION="api-version=2018-09-01-preview"

for i in $(az rest --uri "$URI?$VERSION" --method "GET" | jq '.value[].name' -r); do
    "$BASE_DIR/delete-deployments" "$1" "$i"
    "$BASE_DIR/delete-components" "$1" "$i" 
    az rest --uri "$URI/$i?$VERSION" --method "DELETE"
done