//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package v20230415preview

// AwsCredentialClientCreateOrUpdateResponse contains the response from method AwsCredentialClient.CreateOrUpdate.
type AwsCredentialClientCreateOrUpdateResponse struct {
	AWSCredentialResource
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// AwsCredentialClientDeleteResponse contains the response from method AwsCredentialClient.Delete.
type AwsCredentialClientDeleteResponse struct {
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// AwsCredentialClientGetResponse contains the response from method AwsCredentialClient.Get.
type AwsCredentialClientGetResponse struct {
	AWSCredentialResource
}

// AwsCredentialClientListByRootScopeResponse contains the response from method AwsCredentialClient.ListByRootScope.
type AwsCredentialClientListByRootScopeResponse struct {
	AWSCredentialResourceListResult
}

// AzureCredentialClientCreateOrUpdateResponse contains the response from method AzureCredentialClient.CreateOrUpdate.
type AzureCredentialClientCreateOrUpdateResponse struct {
	AzureCredentialResource
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// AzureCredentialClientDeleteResponse contains the response from method AzureCredentialClient.Delete.
type AzureCredentialClientDeleteResponse struct {
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// AzureCredentialClientGetResponse contains the response from method AzureCredentialClient.Get.
type AzureCredentialClientGetResponse struct {
	AzureCredentialResource
}

// AzureCredentialClientListByRootScopeResponse contains the response from method AzureCredentialClient.ListByRootScope.
type AzureCredentialClientListByRootScopeResponse struct {
	AzureCredentialResourceListResult
}

// PlaneTypesClientGetResponse contains the response from method PlaneTypesClient.Get.
type PlaneTypesClientGetResponse struct {
	PlaneResource
}

// PlanesClientCreateOrUpdateResponse contains the response from method PlanesClient.CreateOrUpdate.
type PlanesClientCreateOrUpdateResponse struct {
	PlaneResource
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// PlanesClientDeleteResponse contains the response from method PlanesClient.Delete.
type PlanesClientDeleteResponse struct {
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// PlanesClientGetResponse contains the response from method PlanesClient.Get.
type PlanesClientGetResponse struct {
	PlaneResource
}

// PlanesClientListByRootScopeResponse contains the response from method PlanesClient.ListByRootScope.
type PlanesClientListByRootScopeResponse struct {
	PlaneResourceListResult
}

// ResourceGroupsClientCreateOrUpdateResponse contains the response from method ResourceGroupsClient.CreateOrUpdate.
type ResourceGroupsClientCreateOrUpdateResponse struct {
	ResourceGroupResource
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ResourceGroupsClientDeleteResponse contains the response from method ResourceGroupsClient.Delete.
type ResourceGroupsClientDeleteResponse struct {
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ResourceGroupsClientGetResponse contains the response from method ResourceGroupsClient.Get.
type ResourceGroupsClientGetResponse struct {
	ResourceGroupResource
}

// ResourceGroupsClientListByRootScopeResponse contains the response from method ResourceGroupsClient.ListByRootScope.
type ResourceGroupsClientListByRootScopeResponse struct {
	ResourceGroupResourceListResult
}

