apiVersion: v1
kind: ServiceAccount
metadata:
  name: radius-api-readiness
  namespace: "{{ .Release.Namespace }}"
  labels:
    control-plane: radius-api-readiness
    app.kubernetes.io/name: radius-api-readiness
    app.kubernetes.io/part-of: radius
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
