# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
---
name: Install Git HTTP Backend
description: Installs a git HTTP backend, configures basic auth, and exposes it inside the cluster using alpine/git.
inputs:
  git-username:
    description: Username for basic authentication
    required: true
  git-password:
    description: Password for basic authentication
    required: true
  namespace:
    description: Namespace to deploy the git-http-backend into
    required: false
    default: git-http-backend
  image:
    description: Container image to use for the git backend
    required: false
    default: alpine/git:2.45.2
runs:
  using: composite
  steps:
    - name: Install git-http-backend
      shell: bash
      run: .github/actions/install-git-http-backend/install-git-http-backend.sh "${INPUTS_GIT_USERNAME}" "${INPUTS_GIT_PASSWORD}" "${INPUTS_NAMESPACE}" "${INPUTS_IMAGE}"
      env:
        INPUTS_GIT_USERNAME: ${{ inputs.git-username }}
        INPUTS_GIT_PASSWORD: ${{ inputs.git-password }}
        INPUTS_NAMESPACE: ${{ inputs.namespace }}
        INPUTS_IMAGE: ${{ inputs.image }}
