// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

package deploy

import (
	"context"

	"github.com/project-radius/radius/pkg/cli/clients"
	ucpresources "github.com/project-radius/radius/pkg/ucp/resources"
)

type PublicEndpoint struct {
	Resource ucpresources.ID
	Endpoint string
}

//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is finding the public endpoints for a given deployment result. It is looping through the resources in the 
//	deployment result and using the DiagnosticsClient to get the public endpoint for each resource. If the endpoint is not 
//	nil, it is added to the endpoints array. Finally, the endpoints array is returned.
//
// </AiDoc: End of OpenAI comments>
func FindPublicEndpoints(ctx context.Context, diag clients.DiagnosticsClient, result clients.DeploymentResult) ([]PublicEndpoint, error) {
	endpoints := []PublicEndpoint{}
	for _, resource := range result.Resources {
		endpoint, err := diag.GetPublicEndpoint(ctx, clients.EndpointOptions{ResourceID: resource})
		if err != nil {
			return nil, err
		}

		if endpoint == nil {
			continue
		}

		endpoints = append(endpoints, PublicEndpoint{Resource: resource, Endpoint: *endpoint})
	}

	return endpoints, nil
}
