//go:build go1.18
// +build go1.18

// Licensed under the Apache License, Version 2.0 . See LICENSE in the repository root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v20220315privatepreview

// ApplicationsClientCreateOptions contains the optional parameters for the ApplicationsClient.Create method.
type ApplicationsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// ApplicationsClientDeleteOptions contains the optional parameters for the ApplicationsClient.Delete method.
type ApplicationsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// ApplicationsClientGetOptions contains the optional parameters for the ApplicationsClient.Get method.
type ApplicationsClientGetOptions struct {
	// placeholder for future optional parameters
}

// ApplicationsClientListByScopeOptions contains the optional parameters for the ApplicationsClient.NewListByScopePager method.
type ApplicationsClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// ApplicationsClientUpdateOptions contains the optional parameters for the ApplicationsClient.Update method.
type ApplicationsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// ContainersClientBeginCreateOptions contains the optional parameters for the ContainersClient.BeginCreate method.
type ContainersClientBeginCreateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// ContainersClientBeginDeleteOptions contains the optional parameters for the ContainersClient.BeginDelete method.
type ContainersClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// ContainersClientBeginUpdateOptions contains the optional parameters for the ContainersClient.BeginUpdate method.
type ContainersClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// ContainersClientGetOptions contains the optional parameters for the ContainersClient.Get method.
type ContainersClientGetOptions struct {
	// placeholder for future optional parameters
}

// ContainersClientListByScopeOptions contains the optional parameters for the ContainersClient.NewListByScopePager method.
type ContainersClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// EnvironmentsClientCreateOptions contains the optional parameters for the EnvironmentsClient.Create method.
type EnvironmentsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// EnvironmentsClientDeleteOptions contains the optional parameters for the EnvironmentsClient.Delete method.
type EnvironmentsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// EnvironmentsClientGetOptions contains the optional parameters for the EnvironmentsClient.Get method.
type EnvironmentsClientGetOptions struct {
	// placeholder for future optional parameters
}

// EnvironmentsClientGetmetadataOptions contains the optional parameters for the EnvironmentsClient.Getmetadata method.
type EnvironmentsClientGetmetadataOptions struct {
	// placeholder for future optional parameters
}

// EnvironmentsClientListByScopeOptions contains the optional parameters for the EnvironmentsClient.NewListByScopePager method.
type EnvironmentsClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// EnvironmentsClientUpdateOptions contains the optional parameters for the EnvironmentsClient.Update method.
type EnvironmentsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// ExtendersClientBeginCreateOptions contains the optional parameters for the ExtendersClient.BeginCreate method.
type ExtendersClientBeginCreateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// ExtendersClientBeginDeleteOptions contains the optional parameters for the ExtendersClient.BeginDelete method.
type ExtendersClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// ExtendersClientBeginUpdateOptions contains the optional parameters for the ExtendersClient.BeginUpdate method.
type ExtendersClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// ExtendersClientGetOptions contains the optional parameters for the ExtendersClient.Get method.
type ExtendersClientGetOptions struct {
	// placeholder for future optional parameters
}

// ExtendersClientListByScopeOptions contains the optional parameters for the ExtendersClient.NewListByScopePager method.
type ExtendersClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// ExtendersClientListSecretsOptions contains the optional parameters for the ExtendersClient.ListSecrets method.
type ExtendersClientListSecretsOptions struct {
	// placeholder for future optional parameters
}

// GatewaysClientBeginCreateOptions contains the optional parameters for the GatewaysClient.BeginCreate method.
type GatewaysClientBeginCreateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// GatewaysClientBeginDeleteOptions contains the optional parameters for the GatewaysClient.BeginDelete method.
type GatewaysClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// GatewaysClientBeginUpdateOptions contains the optional parameters for the GatewaysClient.BeginUpdate method.
type GatewaysClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// GatewaysClientGetOptions contains the optional parameters for the GatewaysClient.Get method.
type GatewaysClientGetOptions struct {
	// placeholder for future optional parameters
}

// GatewaysClientListByScopeOptions contains the optional parameters for the GatewaysClient.NewListByScopePager method.
type GatewaysClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// HTTPRoutesClientBeginCreateOptions contains the optional parameters for the HTTPRoutesClient.BeginCreate method.
type HTTPRoutesClientBeginCreateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// HTTPRoutesClientBeginDeleteOptions contains the optional parameters for the HTTPRoutesClient.BeginDelete method.
type HTTPRoutesClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// HTTPRoutesClientBeginUpdateOptions contains the optional parameters for the HTTPRoutesClient.BeginUpdate method.
type HTTPRoutesClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// HTTPRoutesClientGetOptions contains the optional parameters for the HTTPRoutesClient.Get method.
type HTTPRoutesClientGetOptions struct {
	// placeholder for future optional parameters
}

// HTTPRoutesClientListByScopeOptions contains the optional parameters for the HTTPRoutesClient.NewListByScopePager method.
type HTTPRoutesClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// OperationsClientListOptions contains the optional parameters for the OperationsClient.NewListPager method.
type OperationsClientListOptions struct {
	// placeholder for future optional parameters
}

// SecretStoresClientBeginCreateOptions contains the optional parameters for the SecretStoresClient.BeginCreate method.
type SecretStoresClientBeginCreateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// SecretStoresClientBeginDeleteOptions contains the optional parameters for the SecretStoresClient.BeginDelete method.
type SecretStoresClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// SecretStoresClientBeginUpdateOptions contains the optional parameters for the SecretStoresClient.BeginUpdate method.
type SecretStoresClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// SecretStoresClientGetOptions contains the optional parameters for the SecretStoresClient.Get method.
type SecretStoresClientGetOptions struct {
	// placeholder for future optional parameters
}

// SecretStoresClientListByScopeOptions contains the optional parameters for the SecretStoresClient.NewListByScopePager method.
type SecretStoresClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

// SecretStoresClientListSecretsOptions contains the optional parameters for the SecretStoresClient.ListSecrets method.
type SecretStoresClientListSecretsOptions struct {
	// placeholder for future optional parameters
}

// VolumesClientBeginCreateOptions contains the optional parameters for the VolumesClient.BeginCreate method.
type VolumesClientBeginCreateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// VolumesClientBeginDeleteOptions contains the optional parameters for the VolumesClient.BeginDelete method.
type VolumesClientBeginDeleteOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// VolumesClientBeginUpdateOptions contains the optional parameters for the VolumesClient.BeginUpdate method.
type VolumesClientBeginUpdateOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// VolumesClientGetOptions contains the optional parameters for the VolumesClient.Get method.
type VolumesClientGetOptions struct {
	// placeholder for future optional parameters
}

// VolumesClientListByScopeOptions contains the optional parameters for the VolumesClient.NewListByScopePager method.
type VolumesClientListByScopeOptions struct {
	// placeholder for future optional parameters
}

