// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

package output

const (
	FormatJson    = "json"
	FormatTable   = "table"
	FormatList    = "list"
	DefaultFormat = FormatTable
)

//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	The function SupportedFormats() is returning a list of strings that represent different formats. The list includes the 
//	strings "json", "table", and "list".
//
// </AiDoc: End of OpenAI comments>
func SupportedFormats() []string {
	return []string{
		FormatJson,
		FormatTable,
		FormatList,
	}
}
