// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

package output

import (
	"encoding/json"
	"io"
)

type JSONFormatter struct {
}

//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	
 
//	The previous function is a JSONFormatter which takes an object, a writer, and a FormatterOptions as parameters. It then 
//	marshals the object into a JSON format and writes it to the writer with indentation. Finally, it adds a new line to the 
//	end of the output.
//
// </AiDoc: End of OpenAI comments>
func (f *JSONFormatter) Format(obj any, writer io.Writer, options FormatterOptions) error {
	b, err := json.MarshalIndent(obj, "", "  ")
	if err != nil {
		return err
	}

	_, err = writer.Write(b)
	if err != nil {
		return err
	}

	_, err = writer.Write([]byte("\n"))
	if err != nil {
		return err
	}

	return nil
}

var _ Formatter = (*JSONFormatter)(nil)
