// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

package output

import (
	"fmt"

	ucpresources "github.com/project-radius/radius/pkg/ucp/resources"
)

const (
	ProgressFailed    = "Failed"
	ProgressCompleted = "Completed"
)

var ProgressDefaultSpinner = []string{".  ", ".. ", "..."}

// ShowResource returns true if the resource should be displayed to the user.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	The function is returning a boolean value of true, indicating that the resource with the given ID should be shown.
//
// </AiDoc: End of OpenAI comments>
func ShowResource(id ucpresources.ID) bool {
	return true
}

// FormatResourceForDisplay returns a display string for the resource type and name.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function takes an ID as an argument and returns a string that contains the name and type of the resource associated
//	 with the ID. The name and type are formatted to be 15 and 20 characters long respectively.
//
// </AiDoc: End of OpenAI comments>
func FormatResourceForDisplay(id ucpresources.ID) string {
	return fmt.Sprintf("%-15s %-20s", FormatResourceNameForDisplay(id), FormatResourceTypeForDisplay(id))
}

// FormatResourceForProgressDisplay returns a display string for a progress spinner, resource type, and name.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is creating a format string that can be used to display the name and type of a resource in a progress 
//	tracker. It takes in a resource ID and returns a string that contains the name and type of the resource, formatted for 
//	display in the progress tracker.
//
// </AiDoc: End of OpenAI comments>
func FormatResourceForProgressDisplay(id ucpresources.ID) string {
	// NOTE: this format string creates ... a format string! That's intentional
	// because the progress tracker needs somewhere to put the progress.
	return fmt.Sprintf("%s %-15s %-20s", "%-20s", FormatResourceNameForDisplay(id), FormatResourceTypeForDisplay(id))
}

// FormatResourceNameForDisplay returns a display string for the resource name.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	The function is taking an ID of a resource and returning the name of the resource as a string.
//
// </AiDoc: End of OpenAI comments>
func FormatResourceNameForDisplay(id ucpresources.ID) string {
	// Just show the last segment of the resource name.
	return id.Name()
}

// FormatResourceTypeForDisplay returns a display string for the resource type.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	The function is taking in an ID of a resource and returning the type of the resource as a string.
//
// </AiDoc: End of OpenAI comments>
func FormatResourceTypeForDisplay(id ucpresources.ID) string {
	// It's an ARM resource, use the qualified type.
	return id.Type()
}
