// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

package output

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/require"
)

type writerInput struct {
	Size   string
	IsCool bool
}

// Just a single E2E test for the Write method, writers are tested in detail elsewhere.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	The previous function is creating an object called "writerInput" with two properties, "Size" and "IsCool". It then 
//	creates a buffer and uses the "Write" function to write the object to the buffer in JSON format. Finally, it checks that
//	 the output of the buffer matches the expected output.
//
// </AiDoc: End of OpenAI comments>
func Test_Write(t *testing.T) {
	obj := writerInput{
		Size:   "mega",
		IsCool: true,
	}

	buffer := &bytes.Buffer{}
	err := Write(FormatJson, obj, buffer, FormatterOptions{})
	require.NoError(t, err)

	expected := `{
  "Size": "mega",
  "IsCool": true
}
`
	require.Equal(t, expected, buffer.String())
}
