// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

package azure

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions"
	"github.com/project-radius/radius/pkg/azure/clientv2"
)

// SubscriptionResult is the result of loading Azure subscriptions for the user.
type SubscriptionResult struct {
	Default       *Subscription
	Subscriptions []Subscription
}

// LoadSubscriptionsFromProfile reads the users Azure profile to find subscription data.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	
 
//	This function is loading the subscriptions from the user's profile. It first finds the path of the profile, then loads 
//	the profile from that path. It then creates a SubscriptionResult object and adds all of the enabled subscriptions from 
//	the profile to it. Finally, it sets the default subscription to the one marked as default in the profile.
//
// </AiDoc: End of OpenAI comments>
func LoadSubscriptionsFromProfile() (*SubscriptionResult, error) {
	path, err := ProfilePath()
	if err != nil {
		return nil, fmt.Errorf("cannot load subscriptions from profile: %v", err)
	}

	profile, err := LoadProfile(path)
	if err != nil {
		return nil, fmt.Errorf("cannot load subscriptions from profile: %v", err)
	}

	result := &SubscriptionResult{}
	for _, s := range profile.Subscriptions {
		if s.State != "Enabled" {
			continue
		}

		result.Subscriptions = append(result.Subscriptions, s)

		if s.IsDefault {
			result.Default = &s
		}
	}

	return result, nil
}

// LoadSubscriptionsFromAzure uses ARM to find subscription data.
//
// <AiDoc: The following comments were generated by OpenAI explaining the code as it existed at the time of this commit>
//	This function is loading a list of subscriptions from Azure. It creates a new SubscriptionsClient using the provided 
//	options, then creates a list pager to iterate through the list of subscriptions. For each subscription, it adds the 
//	name, ID, and tenant ID to a SubscriptionResult object, which is then returned.
//
// </AiDoc: End of OpenAI comments>
func LoadSubscriptionsFromAzure(ctx context.Context, options clientv2.Options) (*SubscriptionResult, error) {
	client, err := clientv2.NewSubscriptionsClient(&options)
	if err != nil {
		return nil, err
	}

	pager := client.NewListPager(&armsubscriptions.ClientListOptions{})
	result := &SubscriptionResult{}
	for pager.More() {
		nextPage, err := pager.NextPage(ctx)
		if err != nil {
			return nil, err
		}

		for _, subscription := range nextPage.SubscriptionListResult.Value {
			result.Subscriptions = append(result.Subscriptions, Subscription{
				Name:     *subscription.DisplayName,
				ID:       *subscription.SubscriptionID,
				TenantID: *subscription.TenantID,
			})
		}
	}

	return result, nil
}
