# ------------------------------------------------------------
# Copyright 2026 The Radius Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------

# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: __publish-release

on:
  workflow_call:

permissions: {}

env:
  RELEASE_PATH: ./release

jobs:
  publish-release:
    name: Publish GitHub Release
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: write # Required for creating releases
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: .python-version

      - name: Parse release version and set environment variables
        run: python ./.github/scripts/get_release_version.py

      - name: Download release artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: rad_cli_*
          merge-multiple: true
          path: ${{ env.RELEASE_PATH }}

      - name: generate checksum files
        run: |
          cd "${RELEASE_PATH}" && for i in *; do sha256sum -b "$i" > "$i.sha256"; done && cd -
          ls -l "${RELEASE_PATH}"

      - name: Create GitHub RC Release (pre-release and auto-generate release notes)
        if: ${{ contains(env.REL_VERSION, 'rc') }}
        run: |
          gh release create "v${REL_VERSION}" \
            "${RELEASE_PATH}"/* \
            --title "Radius v${REL_VERSION}" \
            --generate-notes \
            --verify-tag \
            --prerelease
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create GitHub Official Release
        if: ${{ !contains(env.REL_VERSION, 'rc') }}
        run: |
          gh release create "v${REL_VERSION}" \
            "${RELEASE_PATH}"/* \
            --title "Radius v${REL_VERSION}" \
            --notes-file "docs/release-notes/v${REL_VERSION}.md" \
            --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
