# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Test dev container feature

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - deploy/devcontainer-feature/**
      - .github/workflows/devcontainer-feature-test.yaml
    branches:
      - main
  workflow_call:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      matrix:
        baseImage:
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:debian
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Generating tests for Radius CLI (default) against '${{ matrix.baseImage }}'
        run: devcontainer features test --skip-scenarios -f radcli -i "${BASE_IMAGE}" .
        working-directory: ./deploy/devcontainer-feature
        env:
          BASE_IMAGE: ${{ matrix.baseImage }}

  test-scenarios:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Generating tests for radcli scenarios
        run: devcontainer features test -f radcli --skip-autogenerated --skip-duplicated .
        working-directory: ./deploy/devcontainer-feature
